project 'HealthApp.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HealthApp
  pod 'JTAppleCalendar'
  pod 'Charts'
  pod 'FloatingPanel'
  pod 'RealmSwift'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'IQKeyboardManagerSwift'
  
end
